language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t robresma/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true robresma/docker-react npm run test

deploy:
    provider: elasticbeanstack
    region: "us-west-2"
    app: "docker-react"
    env: "DockerReact-env-1"
    bucket_name: "elasticbeanstalk-us-west-2-499388976224"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY