language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t robresma/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true robresma/docker-react npm run test